# Generated by Django 5.2 on 2025-05-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='business_profiles/'),
        ),
    ]
