# Generated by Django 5.2 on 2025-06-03 17:14

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='services',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('cleaning', 'Cleaning'), ('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('landscaping', 'Landscaping'), ('delivery', 'Delivery'), ('painting', 'Painting'), ('carpentry', 'Carpentry'), ('handyman', 'Handyman'), ('other', 'Other')], help_text='Select all services your business offers.', max_length=83),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='services_needed',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('cleaning', 'Cleaning'), ('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('landscaping', 'Landscaping'), ('delivery', 'Delivery'), ('painting', 'Painting'), ('carpentry', 'Carpentry'), ('handyman', 'Handyman'), ('other', 'Other')], max_length=83),
        ),
    ]
