# Generated by Django 5.2.1 on 2025-05-29 23:28

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_businessprofile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequest',
            options={},
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='image',
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='services_needed',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('cleaning', 'Cleaning'), ('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('landscaping', 'Landscaping'), ('delivery', 'Delivery'), ('other', 'Other')], max_length=55),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ServiceRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_requests/')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='client.servicerequest')),
            ],
        ),
    ]
