# Generated by Django 5.2 on 2025-04-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_businessprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='services',
            field=models.CharField(choices=[('cleaning', 'cleaning'), ('plumbing', 'plumbing'), ('electrical', 'electrical'), ('landscaping', 'landscaping'), ('delivery', 'delivery'), ('other', 'other')], max_length=50),
        ),
    ]
