# Generated by Django 5.2 on 2025-04-23 16:09

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_businessprofile_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='services',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('cleaning', 'cleaning'), ('plumbing', 'plumbing'), ('electrical', 'electrical'), ('landscaping', 'landscaping'), ('delivery', 'delivery'), ('other', 'other')], max_length=55),
        ),
    ]
