# Generated by Django 5.2 on 2025-06-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_message_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy')], default='available', help_text='Set your current business status.', max_length=10),
        ),
    ]
