# Generated by Django 5.2 on 2025-04-23 16:25

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_servicerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='services_needed',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('cleaning', 'cleaning'), ('plumbing', 'plumbing'), ('electrical', 'electrical'), ('landscaping', 'landscaping'), ('delivery', 'delivery'), ('other', 'other')], max_length=55),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='title',
            field=models.CharField(default='default title', max_length=100),
        ),
    ]
