# Generated by Django 5.2 on 2025-05-02 00:38

import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0009_messages"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Messages",
            new_name="Message",
        ),
        migrations.AlterModelOptions(
            name="businessprofile",
            options={
                "verbose_name": "Business Profile",
                "verbose_name_plural": "Business Profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="servicerequest",
            options={
                "verbose_name": "Service Request",
                "verbose_name_plural": "Service Requests",
            },
        ),
        migrations.AlterField(
            model_name="businessprofile",
            name="name",
            field=models.CharField(
                help_text="Enter your business name.", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="businessprofile",
            name="service_location",
            field=models.CharField(
                help_text="Where is your business based?", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="businessprofile",
            name="services",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("cleaning", "Cleaning"),
                    ("plumbing", "Plumbing"),
                    ("electrical", "Electrical"),
                    ("landscaping", "Landscaping"),
                    ("delivery", "Delivery"),
                    ("other", "Other"),
                ],
                help_text="Select all services your business offers.",
                max_length=55,
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="participants",
            field=models.ManyToManyField(
                related_name="Chatrooms", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="account_type",
            field=models.CharField(
                choices=[("individual", "Individual"), ("business", "Business")],
                help_text="Select the type of user account.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="description",
            field=models.TextField(help_text="Additional details about the request."),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="location",
            field=models.CharField(
                help_text="Where should the service be delivered?", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="services_needed",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("cleaning", "Cleaning"),
                    ("plumbing", "Plumbing"),
                    ("electrical", "Electrical"),
                    ("landscaping", "Landscaping"),
                    ("delivery", "Delivery"),
                    ("other", "Other"),
                ],
                help_text="Select all services your business offers.",
                max_length=55,
            ),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="title",
            field=models.CharField(
                help_text="Brief title for the request.", max_length=100
            ),
        ),
    ]
